### ISSUE TITLE
`const` qualifiers in API

### ISSUE THREAD

**Issue by JensWehner** [robashaw/libecpint#17]
Hi thanks for the great library.

When I started implementing the filling of the ecps, I noticed that the calls to 

`void compute_shell_pair(ECP &U, GaussianShell &shellA, GaussianShell &shellB, TwoIndex<double> &values, int shiftA = 0, int shiftB = 0);` 

need `non-const` input for `U`,`shellA` and `shellB`. Does the engine actually modify those? 

That would make using parallelization a bit more cumbersome.

**Comment by robashaw** [comment]
The engine doesn't modify those at that point, and I'm honestly not sure why they aren't const references. I'll make a note to change it in the next update (or feel free to make a pull request).
