### ISSUE TITLE
Confusion about the definition of power in ECPGaussians

### ISSUE THREAD

**Issue by JensWehner** [robashaw/libecpint#19]
Hi I am a bit confused about the documentation 

the `n` in ECPGaussians is described as the power of `r^n` but the constructor uses

https://github.com/robashaw/libecpint/blob/79a3aee153039ac04b02aab6cd181db19e9567e2/src/lib/ecp.cpp#L38

and substracts `2` from the power. How does this fit together?

**Comment by robashaw** [comment]
Hi, this is a convention thing that is thoroughly annoying. 

Basically, some ECP formats (most notably those found for the Stuttgart-Dresden ECPs) include the r^2 from the spherical coordinate Jacobian in their definition of $$n$$. The algorithms used to compute the integrals here are in cartesian coordinates so we have to subtract that 2. 

In general $$n-2$$ is almost always zero (pure spherical), although it is occasionally -2 or -1 (in particular for the LANL ECPs). So you can tell from the input format what convention is used: if the values are 0,1,2, then it's the same as here; if its -2,-1,0, you need to add 2. 

Hopefully that explains it. This is the reason I'm trying to build an ECP library into the project, to avoid exactly this confusion, along with some relating to how some ECPs also include additional shells that refer to a different type of potential.

**Comment by JensWehner** [comment]
Thanks for your reply, I will try to give it a shot. :)

**Comment by JensWehner** [comment]
I was just confused by the documentation vs implementation.

**Comment by robashaw** [comment]
Fair, I should probably add a note to the docs, I'll leave this issue up until then.

**Comment by robashaw** [comment]
PR #23 adds this info to the docs.
