### ISSUE TITLE
Error message "Failed to converge:" in calculation on AuI

### ISSUE THREAD

**Issue by thomas-dresselhaus** [robashaw/libecpint#21]
In a calculation on AuI, multiple outputs of an error message "Failed to converge:" appeared, which seem to originate from a grid integration. The program continues to run, but the resulting energy seems to be off by about 1 mHartree.

**Comment by robashaw** [comment]
Please can you give enough detail (bond distance, basis sets, code version) so that I can reproduce the error. The quadrature is adaptive so should only fail to converge if something is going seriously wrong.

**Comment by thomas-dresselhaus** [comment]
Of course, sorry for not providing this information straight away.

The calculation is a standard Hartree--Fock calculation on AuI in the Def2-SVP basis set (as obtained from the widely used basis set exchange). The calculation shows the above error for various bond lengths (2, 3, 4 Angstrom, and also [the optimal bond length of 2.405 Angstrom](https://www.sciencedirect.com/science/article/pii/S1044030502003707)).

The libecpint version used is the most recent master version, i.e. commit fa8df43c0adc7587a4a44b87fc9567a33dcc003d.

**Comment by robashaw** [comment]
This issue is now resolved in the new patch (pr #23). I get no more convergence issues, and an RHF energy that agrees with molpro to the microhartree.
