### ISSUE TITLE
Normalisation of the cartesian shells

### ISSUE THREAD

**Issue by JensWehner** [robashaw/libecpint#25]
Hello,
 sorry to bother again, the shells returned by the integral engine are cartesian functions in the canonical order. Are these unnormalized or are all functions normalized to 1 or only the diagonal elements as in the CCA convention?

**Comment by robashaw** [comment]
They are unnormalised. Although of course if you have normalised via the contraction coefficients that will carry through.

**Comment by JensWehner** [comment]
thanks
