### ISSUE TITLE
v1.0.5 release?

### ISSUE THREAD

**Issue by junghans** [robashaw/libecpint#29]
We are trying to integrate libecp in votca-xtp (https://github.com/votca/xtp/pull/588), but we need the patch from #26, so could you please tag a v1.0.5 release?

I have patched #26 into fedora's rpm and that works for our development.

**Comment by robashaw** [comment]
Done.

**Comment by junghans** [comment]
Superb!!!!!

**Comment by junghans** [comment]
@mbanck, could you bump this in debian please!

**Comment by junghans** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2021-5464f657f7
https://build.opensuse.org/request/show/869614

**Comment by mbanck** [comment]
> @mbanck, could you bump this in debian please!

@junghans done
