### ISSUE TITLE
Prepare commented real-world examples

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [robashaw/libecpint#36]
As part of the [libecpint's JOSS review](https://github.com/openjournals/joss-reviews/issues/3039) I suggest to prepare a couple of examples that solve some (possibly simple) real world problems.

I appreciate that there are already a few high-level tests that users can adapt to write their own code, but they are

1. a bit buried in the source tree;
2. not commented (that is, it's not clear what they do);
3. they are compiled & executed as tests and therefore are not standalone (from a new user's perspective)

In my opinion the simplest thing you could do would be to take one or both high-level tests that are already present (`api_test1` and `api_test2`), comment them lightly (or write a short accompanying README file) and put them in a separate `examples` folder (to be placed in the root folder perhaps?). There should also be a self-contained CMakeLists.txt that shows how to compile a project that uses the lib once it is installed.

**Comment by robashaw** [comment]
An example use with instructions on how to build has been added as part of the linked PR.

**Comment by lorenzo-rovigatti** [comment]
Thank you! Just a warning: the suggested way of compiling the example does not work on my machine (where I tried with both `zsh` and `bash`). I had to remove the square brackets, that is, change from

```
cmake .. [-DCMAKE_CXX_FLAGS="-I/home/lorenzo/installazioni/include -std=c++14"] [-DCMAKE_EXE_LINKER_FLAGS="-L/home/lorenzo/installazioni/lib"]
```

to

```
cmake .. -DCMAKE_CXX_FLAGS="-I<include_dir> -std=c++14"] -DCMAKE_EXE_LINKER_FLAGS="-L<lib_dir>"
```
