### ISSUE TITLE
v1.0.6 says it is v1.0.5 in cmake

### ISSUE THREAD

**Issue by junghans** [robashaw/libecpint#45]
https://github.com/robashaw/libecpint/blob/4ad71a84ee9e3febce25bbe46b01a1dfd9dc883c/CMakeLists.txt#L22

so even if v1.0.6 is installed cmake will pick it up as v1.0.5.

**Comment by robashaw** [comment]
I have moved the old v1.0.6 to v1.0.6a and re-released v1.0.6 with the correct versioning in CMakeLists
