### ISSUE TITLE
Faddeeva to cerf 

### ISSUE THREAD

**Issue by loriab** [robashaw/libecpint#53]
Psi4 folks were looking into the cerf project https://jugit.fz-juelich.de/mlz/libcerf as a replacement for libFaddeeva. It has somewhat better packaging characteristics and is already available on conda-forge. Your buildsys for libFaddeeva works great but often packagers don’t like dependencies distributed with libraries. Any thoughts or warnings?

**Comment by loriab** [comment]
fwiw, I think I've got choose-your-lib-faddeeva-or-cerf working locally. all tests that don't need xml pass. :-)

**Comment by robashaw** [comment]
Done by PR #55
