### ISSUE TITLE
API for Adjusting Numerical Threshholds

### ISSUE THREAD

**Issue by JonathonMisiewicz** [robashaw/libecpint#56]
Hi, I'm one of the Psi4 developers.

Recently, we've had a bug report of [inconsistencies](https://github.com/psi4/psi4/issues/2564) between our ECPs (computed using your library) and PySCF. As part of my investigation, I would like to use `libecpint` using more stringent threshholds for prescreening, numerical integration, etc. Sadly, the optional settings where these likely are is [not documented](https://libecpint.readthedocs.io/en/latest/usage.html#settings).

What options does `libecpint` give us to control tightness of the integrals?

**Comment by robashaw** [comment]
Hi, thanks for the message. 

I see that the referenced issue is closed, and the errors had nothing to do with libecpint in the end.

The documentation for options has been updated in the (as-of-yet unmerged) version 1.1 PR, so I'm closing this issue. That said, in case you need to know right now, Psi4 is using the lower level API for which the already-available [code documentation](https://libecpint.readthedocs.io/en/latest/api/classlibecpint_1_1_e_c_p_integral.html#exhale-class-classlibecpint-1-1-e-c-p-integral) states how to set the integration thresholds, and change the size of the radial integration grids.
