### ISSUE TITLE
Consider requiring C++14

### ISSUE THREAD

**Issue by musicinmybrain** [robashaw/libecpint#58]
Since [version 1.13.0](https://github.com/google/googletest/releases/tag/v1.13.0), GoogleTest requires at least C++14. I think (but don’t have a very handy way to verify) that the minimum GCC version for this library,

https://github.com/robashaw/libecpint/blob/f07f8b963d3719ec2667879fceb49deb4e2c6826/README.md?plain=1#L48

should support C++14, so maybe it’s time to just make that the requirement by adjusting

https://github.com/robashaw/libecpint/blob/f07f8b963d3719ec2667879fceb49deb4e2c6826/CMakeLists.txt#L5

to C++14 instead of C++11.

What do you think?

**Comment by junghans** [comment]
I made #59, which forces C++11 only on the target, so one can then overwrite `CMAKE_CXX_STANDARD` however needed.

Moving to C++14 would be a good idea additionally.
